Tensorflow kütüphanesini kullanamka için önce import ediyoruz. tf kısıltmasıyla kullanmak için as tf şeklinde belirtiyoruz. Hangi verisyona sahip olduğumuuzu kontrol edelim

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


Tensor'ler nedir anlamaya caislim

In [2]:
scalar = tf.constant(11)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=11>

Basit bir tensor olusturduk simdi bunun boyutuna(dimensions) bakalim

In [3]:
scalar.ndim 
#ndim = number of dimensions

0

Simdi de bir vektor olusturalim

In [4]:
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

Vektorumuzun boyutunu kontrol edelim

In [5]:
vector.ndim

1

Matris olusturalim

In [12]:
matrix = tf.constant([[1,2],
                     [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

Shape gordugunuz gibi 2 ye 2 bir matris olusturdugumuzu gosteriyor. Simdi matrisimizin boyutuna bakalim.

In [13]:
matrix.ndim

2

Daha spesifik bir matris tanimlayalim

In [14]:
another_matrix = tf.constant([[10.,11],
                              [12,13],
                              [14,15]] , dtype = tf.float16) #spesifik bir veri tipi tanimladik

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 11.],
       [12., 13.],
       [14., 15.]], dtype=float16)>

3x2 lik bir matris olusturugumuzu goruyoruz. Boyutuna bakalim

In [15]:
another_matrix.ndim

2

Tensor Olsuturmaya baslayim

In [16]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

Shape kisminda gordugunuz gibi (3, 2, 3) seklinde bir ciktimiz var bunu 3 tane 3x2 lik matrismiz varmis gibi dusunebilirsiniz. Boyutuna bakalim


In [17]:
tensor.ndim

3

## Son toparlama 
Yukarida olusturduklarimiz aslinda hepsi birer tensor idi. 

* scalar : matematikten bildigimiz skaler ,sadece bir sayi 
* vector : fizikte de gordugumuz vektor bir sayi ve yon bilgisi vardir.
* matrix : universitede lineer cebirde ki matirs NxN sayi dizisinde olusur
* tensor : n-boyutlu sayi dizisidir

Ilk 3 madde de aslinda tensordur fakat boyutlara sahiplerdir